spring:
  application:
    name: reservio-gateway
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  port: 8080