POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: reservio
DB_URL: localhost:5432


spring:
  application:
    name: reservio-gateway
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://${DB_URL}/${POSTGRES_DB}
    username: postgres
    password: postgres
server:
  port: 8080