services:
  postgres:
    container_name: reservio
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
    ports:
      - "5432:5432"
    networks:
      - postgres
      - reservio-net
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - reservio-net
      - postgres
  user-management:
    container_name: user_management
    image: user-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
      DB_URL: reservio:5432
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postgres
      - reservio-net
  account-management:
    container_name: account_management
    image: account-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
      DB_URL: reservio:5432
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postgres
      - reservio-net
  order-management:
    container_name: order_management
    image: order-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
      DB_URL: reservio:5432
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postgres
      - reservio-net
  payment-management:
    container_name: payment_management
    image: payment-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
      DB_URL: reservio:5432
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postgres
      - reservio-net
  product-catalog-management:
    container_name: product_catalog_management
    image: product-catalog-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
      DB_URL: reservio:5432
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postgres
      - reservio-net
  reservation-management:
    container_name: reservation_management
    image: reservation-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
      DB_URL: reservio:5432
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postgres
      - reservio-net
  restaurant-management:
    container_name: restaurant_management
    image: restaurant-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
      DB_URL: reservio:5432
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postgres
      - reservio-net
  storage-management:
    container_name: storage_management
    image: storage-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
      DB_URL: reservio:5432
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postgres
      - reservio-net
  subscription-management:
    container_name: subscription_management
    image: subscription-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
      DB_URL: reservio:5432
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postgres
      - reservio-net
  common:
    container_name: common
    image: common
    networks:
      - reservio-net
#  reservio-gateway:
#    image: reservio-gateway:latest
#    container_name: reservio_gateway
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#      - postgres
#    depends_on:
#      - postgres
#      - rabbitmq

networks:
  postgres:
    driver: bridge
  reservio-net:
    driver: bridge
volumes:
  postgres: