services:
  postgres:
    container_name: reservio
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
    ports:
      - "5432:5432"
    networks:
      - postgres
      - reservio-net
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
  user-management:
    container_name: user_management
    image: user-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservio
      DB_URL: reservio:5432
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - postgres
      - reservio-net
#  reservio-gateway:
#    image: reservio-gateway:latest
#    container_name: reservio_gateway
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#      - postgres
#    depends_on:
#      - postgres
#      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  reservio-net:
    driver: bridge
volumes:
  postgres: