POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: reservio
DB_URL: localhost:5432

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: 123456
