POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: reservio
DB_URL: localhost:5432


EUREKA_ENABLED: true
EUREKA_URL: http://localhost:8761/eureka

#ACCOUNT_MANAGEMENT_URL: http://localhost:9000
#ORDER_MANAGENEMENT_URL: http://localhost:9001
#PRODUCT_CATALOG_MANAGENEMENT_URL: http://localhost:9004
#RESERVATION_MANAGENEMENT_URL: http://localhost:9005
#RESTAURANT_MANAGENEMENT_URL: http://localhost:9006
#STORAGE_MANAGENEMENT_URL: http://localhost:9007
#SUBSCRIPTION_MANAGENEMENT_URL: http://localhost:9008
#USER_MANAGENEMENT_URL: http://localhost:9009
#PAYMENT_MANAGEMENT_URL: http://localhost:9003

ACCOUNT_MANAGEMENT_URL: lb://ACCOUNT-MANAGEMENT
ORDER_MANAGEMENT_URL: lb://ORDER-MANAGEMENT
PAYMENT_MANAGEMENT_URL: lb://PAYMENT-MANAGEMENT
PRODUCT_CATALOG_MANAGEMENT_URL: lb://PRODUCT-CATALOG-MANAGEMENT
RESERVATION_MANAGEMENT_URL: lb://RESERVATION-MANAGEMENT
RESTAURANT_MANAGEMENT_URL: lb://RESTAURANT-MANAGEMENT
STORAGE_MANAGEMENT_URL: lb://localhost:9007
SUBSCRIPTION_MANAGEMENT_URL: lb://SUBSCRIPTION-MANAGEMENT
USER_MANAGEMENT_URL: lb://USER-MANAGEMENT



app:
  queue:
    name: gateway
  urls:
    account-management: ${ACCOUNT_MANAGEMENT_URL}
    order-management: ${ORDER_MANAGEMENT_URL}
    payment-management: ${PAYMENT_MANAGEMENT_URL}
    product-catalog-management: ${PRODUCT_CATALOG_MANAGEMENT_URL}
    reservation-management: ${RESERVATION_MANAGEMENT_URL}
    restaurant-management: ${RESTAURANT_MANAGEMENT_URL}
    storage-management: ${STORAGE_MANAGEMENT_URL}
    subscription-management: ${SUBSCRIPTION_MANAGEMENT_URL}
    user-management: ${USER_MANAGEMENT_URL}

spring:
  application:
    name: gateway-reservio
  datasource:
    url: jdbc:postgresql://${DB_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
    enabled: ${EUREKA_ENABLED}
server:
  port: 8080


