POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: reservio
DB_URL: localhost:5432

EUREKA_ENABLED: true
EUREKA_URL: http://localhost:8761/eureka

ACCOUNT_MANAGEMENT_URL: http://ACCOUNT-MANAGEMENT/accountManagement
ORDER_MANAGEMENT_URL: http://ORDER-MANAGEMENT/orderManagement
PAYMENT_MANAGEMENT_URL: http://PAYMENT-MANAGEMENT/paymentManagement
PRODUCT_CATALOG_MANAGEMENT_URL: http://PRODUCT-CATALOG-MANAGEMENT/productCatalogManagement
RESERVATION_MANAGEMENT_URL: http://RESERVATION-MANAGEMENT/reservationManagement
RESTAURANT_MANAGEMENT_URL: http://RESTAURANT-MANAGEMENT/restaurantManagement
STORAGE_MANAGEMENT_URL: http://STORAGE-MANAGEMENT/storageManagement
SUBSCRIPTION_MANAGEMENT_URL: http://SUBSCRIPTION-MANAGEMENT/subscriptionManagement
USER_MANAGEMENT_URL: http://USER-MANAGEMENT/userManagement

app:
  queue:
    name: payment
  jwt-secret:
    123456789ig
  urls:
    account-management: ${ACCOUNT_MANAGEMENT_URL}
    order-management: ${ORDER_MANAGEMENT_URL}
    product-catalog-management: ${PRODUCT_CATALOG_MANAGEMENT_URL}
    reservation-management: ${RESERVATION_MANAGEMENT_URL}
    restaurant-management: ${RESTAURANT_MANAGEMENT_URL}
    storage-management: ${STORAGE_MANAGEMENT_URL}
    subscription-management: ${SUBSCRIPTION_MANAGEMENT_URL}
    user-management: ${USER_MANAGEMENT_URL}
    payment-management: ${PAYMENT_MANAGEMENT_URL}

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          max-interval: 10s
          multiplier: 2
  security:
    user:
      name: admin
      password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true



server:
  port: 9003


